# Generated by Django 5.0 on 2023-12-12 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='men',
            options={'verbose_name_plural': 'Men'},
        ),
        migrations.AlterField(
            model_name='men',
            name='stars',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
