# Generated by Django 5.0 on 2023-12-12 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kids',
            options={'verbose_name_plural': 'Kids'},
        ),
    ]
